import React, { useState, useEffect } from 'react';
// Styles
import './App.scss';
// Data & external methods
import { FiveGTimeline, retainTalent, shopSlider, forefront, basicSlider } from './data';
import analytics from './helpers/analytics';

// Components
import Header from './components/Header';
import Hero from './components/Hero';
import Pagebody from './components/Pagebody';
import Dropcap from './components/Dropcap';
import Pullquote from './components/Pullquote';
import CTA from './components/CTA';
import Button from './components/Button';
import Timeline from './components/Timeline';
import Slider from './components/Slider';
import Related from './components/Related';
import Credits from './components/Credits';
import Footer from './components/Footer';
import Socials from './components/Socials';
import AnimationTrigger from './components/AnimationTrigger';
import Bubbles from './components/Bubbles';
import Flipboard from './components/Flipboard';
import VerticalSlider from './components/VerticalSlider';
import BasicSlider from './components/BasicSlider';

// Assets
import ladder from './assets/titles/ladder.svg';
import globe from './assets/titles/globe.svg';
import dumbbell from './assets/titles/dumbbell.svg';
import plane from './assets/titles/plane.svg';
import trophy from './assets/titles/trophy.svg';
import Broughttyb from './components/Broughttyb';
import stars from './assets/stars.svg';
import climate from './assets/titles/climate.svg';
import risks from './assets/titles/risks.svg';
import collaborate from './assets/titles/collaborate.svg';
import success from './assets/titles/success.svg';
import change from './assets/titles/change.svg';
import innovation from './assets/titles/innovation.svg';


function App() {
  const [progress, setProgress] = useState(0);

  const changeProgress = () => {
    window.requestAnimationFrame(() => {
      let progressState = progress;
      const docHeight = document.body.scrollHeight;
      const scrolled = window.scrollY + window.innerHeight;
      const difference = docHeight + scrolled;
      const percentage = difference / docHeight - 1;
      progressState = percentage;
      setProgress(progressState);
    });
  };

  useEffect(() => {
    // on update
    document.addEventListener('scroll', changeProgress);
    return function cleanup() {
      document.removeEventListener('scroll', changeProgress);
    };
  });

  useEffect(() => {
    analytics.send('App Loaded');
  }, []);

  return (
    <>
      <Header progress={progress} />
      <Hero />
      <Pagebody>
        <AnimationTrigger>
          <p>
            <Dropcap>I</Dropcap>
            In the year to May 2019, British exports hit £647.1bn, with goods exports rising 4.7pc to £357.1bn.
          </p>
          <p>
            And the UK services sector enjoyed a 3.3pc increase in exports, bringing the UK’s trade surplus in services to £107.3bn.
          </p>
          <p>
            Dr Liam Fox, the outgoing International Trade Secretary, said in July: “Despite the global headwinds getting stronger, today’s record-breaking statistics highlight what a real international trade policy can deliver for the UK.”
          </p>
          <p>
            In 2017, 30pc of Britain’s GDP was generated by exports, prompting the Government to announce an ambitious goal to raise this to 35pc via a campaign to educate, connect and finance small businesses.
          </p>
          <p>
            Despite worrying signs from the global economy, UK exporters continue to boom, helped not only by the weak pound but also by Britain’s strength in sectors such as technology, which exported £55bn of goods and services in the 12 months to May this year.
          </p>
          <p>
            David Salter, head of funded trade finance at NatWest, says: “Despite the uncertainty caused by Brexit and various inter-country trade wars across the globe, the benefits of tapping into a foreign market with strong demand could be game-changing for businesses.”
          </p>
        </AnimationTrigger>
      </Pagebody>
      <VerticalSlider />
      <Pagebody title="The benefits of exporting" img={climate}>
        <AnimationTrigger>
        <p>
        The benefits of exporting do not begin and end with simply finding new customers, explains Mr Salter, of NatWest.
        </p>
        <p>
          He says: “Selling your goods to other countries will lessen your dependence on your domestic market. You are spreading your risk and the fate of your business no longer relies solely on local contracts.”
        </p>
        </AnimationTrigger>
        <AnimationTrigger>
          <Pullquote notopborder>
            <h3>
            Reduced production costs
            </h3>
            <p>
              “If the foreign market is big enough, this demand could help you reduce your production costs and increase your profit margin further,” explains Mr Salter. Your price per unit of manufacture may benefit from economies of scale, but this needs to be offset against the increased costs of distribution[MC(M1] .”
            </p>
          </Pullquote>
        </AnimationTrigger>
        <AnimationTrigger>
          <Pullquote notopborder>
            <h3>
              More resilience
            </h3>
            <p>
            Companies that export goods are more resilient when recessions strike, says Stuart Lisle, tax partner at business advisory company BDO. When business slows down in one territory, exporters can find greater opportunities elsewhere, he says. “The more markets a business sells into, the less impacted they are when certain markets aren’t doing as well, making them more economically resilient.”
            </p>
          </Pullquote>
        </AnimationTrigger>
        <AnimationTrigger>
          <Pullquote notopborder>
            <h3>
              Higher competitiveness
            </h3>
            <p>
              Businesses that export are more competitive, create more jobs and pay higher wages, says Louis Taylor, chief executive of UK Export Finance (UKEF).
              Mr Taylor says: “The benefits of exporting are easy to see – a company of any size can increase sales and revenue, enhance competitiveness and overcome domestic market saturation by finding new overseas customers.”
            </p>
          </Pullquote>
        </AnimationTrigger>
        <AnimationTrigger>
          <Pullquote notopborder>
            <h3>
            Increased productivity
            </h3>
            <p>
              Making the decision to export delivers benefits very quickly, and they continue over time, says Lesley Batchelor, director-general of the Institute of Export & International Trade.

              Ms Batchelor says: “Exporting is shown to increase the productivity of a business up to 34pc in the first year, and then a continuing benefit of 11pc is shown to strengthen businesses against downturns in economic terms.”
            </p>
          </Pullquote>
        </AnimationTrigger>
      </Pagebody>
      <Flipboard />
      <Pagebody
        title="How to take the right risks for your business to survive"
        img={risks}
      >
        <AnimationTrigger>
        </AnimationTrigger>
      </Pagebody>
      <VerticalSlider />
      <Pagebody
        title="Why businesses need to collaborate"
        img={collaborate}
      >
      </Pagebody>
      <BasicSlider title="How to future-proof your company" dataProp={basicSlider} columns={false} />
      <Pagebody
        title="Five of the most successful cross-sector collaborations"
        img={success}
      >
        
      </Pagebody>
      <Pagebody
        title="How different sectors are adapting to digital change"
        img={change}
        noPadding
      >

      </Pagebody>
      <BasicSlider title="Meet the businesses at the forefront of the digital revolution" dataProp={forefront} columns />
      <Pagebody
        title="Innovation is a team sport"
        img={innovation}
      >
      </Pagebody>
      <CTA>
        <p>To find out more about getting your business future fit, visit the NatWest Business Hub</p>
        <Button
          link="https://ad.doubleclick.net/ddm/trackclk/N8083.124621MSNUK/B22370404.240723500;dc_trk_aid=443465896;dc_trk_cid=105350124;dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua="
        />
      </CTA>
      <Socials />
      <Broughttyb />
      <Credits />
      <Related />
      <Footer />
    </>
  );
}

export default App;
